name: "UESTC Online Judge System"
description: "UESTC ACM/ICPC Online Judge system"

url: "http://uestc-acm.github.io/CDOJ"

markdown: kramdown
permalink: pretty
highlighter: pygments

sass:
  style: :compressed
